name: scc403
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - scikit-learn
  - pytorch
  - torchvision
  - umap-learn
  - jupyterlab
  - matplotlib
  - pandas
  - ipywidgets
  - seaborn
  - pandoc
  - notebook
  - pmdarima
